# Generated by Django 5.1.4 on 2026-05-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='showcase_ch_room_5acde8_idx',
            old_name='showcase_chat_room_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='showcase_ta_status_a3289e_idx',
            old_name='showcase_task_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='showcase_ta_sort_or_9b811d_idx',
            old_name='showcase_task_sort_order_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='showcase_ta_due_dat_cb0781_idx',
            old_name='showcase_task_due_date_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedmedia',
            new_name='showcase_up_mime_ty_15a8ca_idx',
            old_name='showcase_media_mime_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedmedia',
            new_name='showcase_up_is_proc_544e16_idx',
            old_name='showcase_media_processed_idx',
        ),
    ]
